language: csharp
solution: IonDotnet.sln
dotnet: 2.1
mono: none

git:
  submodules: false

before_install:
  - sed -i 's/git@github.com:/https:\/\/github.com\//' .gitmodules
  - git submodule update --init --recursive


script:
  - git submodule init
  - git submodule update
  - cd IonDotnet.Tests
  - dotnet test IonDotnet.Tests.csproj -f netcoreapp2.0
  - dotnet test IonDotnet.Tests.csproj -f netcoreapp2.1
  - cd ..