language: csharp
solution: IonDotnet.sln
dotnet: 2.1
mono: none

git:
  submodules: false
  
before_install:
  - sed -i 's/git@github.com:/https://github.com/amzn/ion-tests.git//' .gitmodules
  - git submodule update --init --recursive

script:
  - dotnet build
  - cd IonDotnet.Tests
  - dotnet test
  - cd ..