language: csharp
solution: IonDotnet.sln
dotnet: 2.1
mono: none

addons:
  ssh_known_hosts:
    - 192.30.253.112
  
script:
  - git submodule init
  - git sumodule update
  - dotnet build
  - cd IonDotnet.Tests
  - dotnet test
  - cd ..